"""PsudoCode
Load the processed data (from data/processed/ generated by run_data_processing.py).

Use gan_data_handler.py to segregate the data by operating region.

For each operating region (or at least the minority ones), initialize and train a GAN using gan_model.py and gan_trainer.py.

Once trained, use the Generators from the minority regions to generate synthetic data.

Use gan_data_handler.py again to combine the original data with the synthetic data, creating a new, balanced dataset.

Save this augmented and balanced dataset to a new location within data/processed/ (e.g., data/processed/augmented_data.pkl)."""
